stages:
  process_data:
    cmd: python src/data_process.py
    deps:
    - data/raw
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - data/processed
    outs:
    - models/model.pkl
  eval:
    cmd: python src/eval.py
    deps:
    - data/processed
    - models/model.pkl
    metrics:
      - metrics/metrics.json:
          cache: false
